name: Build apt repo
on:
  workflow_dispatch:

concurrency:
  group: the-only-group
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Import signing key and configure GPG
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg

          echo "${{ secrets.PGP_KEY_AUTOMATA }}" | gpg --batch --import
          echo 'pinentry-mode loopback'  >> ~/.gnupg/gpg.conf
          echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent

          FPR=$(gpg --list-secret-keys --with-colons | awk -F: '$1=="fpr"{print $10;exit}')
          echo "${FPR}:6:" | gpg --batch --import-ownertrust

          git config --global user.signingkey "$FPR"
          git config --global user.name "Caraneer Automata"
          git config --global user.email "182278465+caraneer-automata@users.noreply.github.com"
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true

      - name: Build & install bootstrap debs (mount via SSHFS)
        env:
          SSH_HOST: ${{ env.SSH_HOST }}
          SSH_USER: ${{ env.SSH_USER }}
          SSH_REMOTE_PATH: ${{ env.SSH_REMOTE_PATH }}
          SSH_MOUNT_PATH: /tmp/caraneer-infra-shared
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          ./scripts/bootstrap.sh

      - name: Populate apt repo
        env:
          WEBROOT_DIR: /tmp/caraneer-infra-shared/www/deb
        run: |
          ./scripts/start.sh
